import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const ctx = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 3 });
const page = await ctx.newPage();

await page.goto('http://localhost:3000/?lang=kn', { waitUntil: 'networkidle' });
const info = await page.evaluate(() => {
  const out = {};
  const q = (s) => document.querySelector(s);
  const box = (el) => { if(!el) return null; const r = el.getBoundingClientRect(); return {x:+r.x.toFixed(1),y:+r.y.toFixed(1),w:+r.width.toFixed(1),h:+r.height.toFixed(1)}; };
  const cs = (el, props) => { if(!el) return null; const c = getComputedStyle(el); const o={}; for(const p of props) o[p]=c.getPropertyValue(p); return o; };
  out.htmlLang = document.documentElement.lang;
  out.contentLang = document.querySelector('[lang]')?.getAttribute('lang');
  const track = q('[role="group"][aria-label="Language"]');
  out.track = box(track);
  out.trackCS = cs(track, ['padding','gap','border-radius','min-height','backdrop-filter','background-image']);
  out.segs = [...track.querySelectorAll('a')].map(a => ({t:a.textContent.trim(), box: box(a), offsetLeft: a.offsetLeft, ...cs(a,['padding','min-height','font-size','letter-spacing'])}));
  const thumb = track.querySelector('span[aria-hidden]');
  out.thumb = { box: box(thumb), offsetLeft: thumb?.offsetLeft, style: thumb?.getAttribute('style') };
  out.trackOffsetParent = thumb?.offsetParent?.className;
  const card = q('a[href*="/create/"]');
  out.card = box(card);
  out.cardCS = cs(card, ['border-radius','padding','backdrop-filter','background-image','box-shadow','contain']);
  const poster = card.querySelector('div');
  out.poster = box(poster);
  out.posterCS = cs(poster, ['border-radius','aspect-ratio','box-shadow']);
  out.cardTitle = cs(card.querySelector('h2'), ['font-size','line-height','letter-spacing','color','font-weight']);
  out.cardTitleBox = box(card.querySelector('h2'));
  out.meta = { ...cs(card.querySelector('p:last-of-type'),['font-size','color','line-height']), box: box(card.querySelector('p:last-of-type')), text: card.querySelector('p:last-of-type').textContent };
  const h1 = q('h1');
  out.h1 = { ...cs(h1,['font-size','line-height','letter-spacing','font-weight','max-width']), box: box(h1) };
  const nav = q('header');
  out.nav = { box: box(nav), ...cs(nav,['backdrop-filter','background-image','box-shadow','border-bottom','padding-top','position']) };
  const rootCS = getComputedStyle(document.documentElement);
  out.tokens = {};
  for (const k of ['--glass','--scene-tint-a','--color-scene-base','--color-ink','--color-accent','--color-accent-text','--tracking','--lh-scale','--radius-card','--radius-field']) out.tokens[k]=rootCS.getPropertyValue(k);
  const sceneCS = getComputedStyle(q('.scene'));
  out.scene = { bg: sceneCS.backgroundColor, img: sceneCS.backgroundImage.slice(0,300) };
  // rim pseudo
  out.cardRim = getComputedStyle(card, '::before').backgroundImage;
  out.cardSheen = getComputedStyle(card, '::after').backgroundImage;
  out.cardRimPad = getComputedStyle(card, '::before').padding;
  out.gaps = box(document.querySelectorAll('a[href*="/create/"]')[1]);
  out.footer = cs(q('footer'), ['font-size','color']);
  return out;
});
console.log(JSON.stringify(info, null, 1));
await browser.close();
